services:
    phil_e_taylor_doctrine_encrypt.orm_subscriber:
        class: PhilETaylor\DoctrineEncrypt\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", "%phil_e_taylor_doctrine_encrypt.encryptor_class_name%", "%phil_e_taylor_doctrine_encrypt.secret_key%"]
        tags:
            -  { name: doctrine.event_subscriber }

    phil_e_taylor_doctrine_encrypt.subscriber:
        alias: phil_e_taylor_doctrine_encrypt.orm_subscriber

    phil_e_taylor_doctrine_encrypt.encryptor:
        class: PhilETaylor\DoctrineEncrypt\Services\Encryptor
        arguments:
            - "%phil_e_taylor_doctrine_encrypt.encryptor_class_name%"
            - "%phil_e_taylor_doctrine_encrypt.secret_key%"